name: Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x]
        redis-version: [6]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Setup redis
      uses: shogo82148/actions-setup-redis@v1
      with:
        redis-version: ${{ matrix.redis-version }}
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test ./... -race -covermode=atomic -coverprofile=coverage.out -shuffle=on
    - name: Upload to codecov.io
      if: ${{ success() && matrix.os=='macos-latest' }}
      run: bash <(curl -s https://codecov.io/bash)
    - name: Trigger next workflow
    # Since macOS is last OS in the matrix we only build
    # the docker image after all test passed
      if: ${{ success() && matrix.os=='macos-latest' }}
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_GHA_PAT }}
        repository: ${{ github.repository }}
        event-type: trigger-docker-build
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
